import Head from 'next/head'
import { Inter } from '@next/font/google'
import FormRegister from '@/components/Register/FormRegister';

const inter = Inter({ subsets: ['latin'] })

export default function Register() {
  return (
    <>
      <Head>
        <title>Registrasi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/static/icon/logo.png" />
      </Head>
      <FormRegister />
    </>
  )
}
